### ISSUE TITLE
Server Chan cant sent text due a bug

### ISSUE THREAD

**Issue by chinapsk** [Chardo-v/NEU-AutoSign#1]
You may need to change
`requests.get('https://sc.ftqq.com/yourToken',params = dict(text='Bonjour, Sir.',desp='AutoSign completed successfully.')) `
to
`requests.get('https://sc.ftqq.com/yourToken.send',params = dict(text='Bonjour, Sir.',desp='AutoSign completed successfully.')) `
Nice work dude.

**Comment by Chardo-v** [comment]
Thank you for your comment!
Source file has been corrected.
